### ISSUE TITLE
Can you compile under .NET Standard 2.0?

### ISSUE THREAD

**Issue by DestroyerDarkNess** [arklumpus/CSharpEditor#1]
I mean if it is possible to use it under .net framework.

**Comment by arklumpus** [comment]
Hi! I have just published on NuGet a pre-release version (1.1.3-a7) that has been modified to work with .NET Standard 2.0.

I tried it with .NET Framework 4.8 and it seems to be working fine (though I did get an AccessViolationException while closing the window, but it's thrown by SkiaSharp, so I don't think it's related to the library).

**Comment by DestroyerDarkNess** [comment]
It's not published yet, I'll wait for the new version to appear.

Thanks.

**Comment by DestroyerDarkNess** [comment]
It's giving me this error, and I have no idea what it is.

Could you pass me all the dll, compressed?

```
Install-Package : The attribute "Visible" in element <Content> is unrecognized.  E:\Projects\----\packages\HarfBuzzS
harp.NativeAssets.WebAssembly.2.8.2-preview.178\build\netstandard1.0\HarfBuzzSharp.NativeAssets.WebAssembly.targets
At line:1 char:1
+ Install-Package CSharpEditor -Version 1.1.3-a7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageComm 
   and
 
```

**Comment by arklumpus** [comment]
I have no idea what that error means, have you tried to "install" the package manually (i.e., by adding `<PackageReference Include="CSharpEditor" Version="1.1.3-a7" />` to the `.csproj` file)?

In any case, you can get the DLL by downloading the package directly from NuGet (go to https://www.nuget.org/packages/CSharpEditor/1.1.3-a7 and click on "Download package" on the right), then renaming it with a .ZIP extensions and extracting it. The DLL is in `lib/netstandard2.0` within the archive.

You will also need to add the following NuGet package references:

```XML
    <PackageReference Include="Avalonia" Version="0.10.13" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.13" />
    <PackageReference Include="DiffPlex" Version="1.7.1" />
    <PackageReference Include="IntellisenseIcon" Version="1.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.1.0" />
    <PackageReference Include="System.CodeDom" Version="6.0.0" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.3" />
    <PackageReference Include="VectSharp.Canvas" Version="2.5.1" />
```
